cart/urls.py
from	django.urls	import	path
from	.	import	views
app_name	=	'cart'
urlpatterns	=	[
				path('',	views.cart_detail,	name='cart_detail'),
				path('add/<int:product_id>/',
									views.cart_add,
									name='cart_add'),
				path('remove/<int:product_id>/',
									views.cart_remove,
									name='cart_remove'),
]

orders/urls.py
from	.	import	views
from	django.urls	import	path

app_name	=	'orders'
urlpatterns	=	[
				path('create/',	views.order_create,	name='order_create'),
]

shopping/urls.py
from django.contrib import admin
from django.urls import path,include
from	django.conf	import	settings
from	django.conf.urls.static	import	static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',   include('cart.urls',    namespace='cart')),
    path('orders/', include('orders.urls',  namespace='orders')),
    path('',	include('shoppingCart.urls',	namespace='shop')),
]
if	settings.DEBUG:
    urlpatterns	+=	static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shoppingCart/urls.py
from	django.urls	import	path
from	.	import	views
app_name	=	'shoppingCart'
urlpatterns	=	[
	path('',	views.product_list,	name='product_list'),
	path('<slug:category_slug>/',	views.product_list,	
						name='product_list_by_category'),
	path('<int:id>/<slug:slug>/',	views.product_detail,
						name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
from	shoppingCart.models	import	Product
# Create your models here.
class	Order(models.Model):
				first_name	=	models.CharField(max_length=50)
				last_name	=	models.CharField(max_length=50)
				email	=	models.EmailField()
				address	=	models.CharField(max_length=250)
				postal_code	=	models.CharField(max_length=20)
				city	=	models.CharField(max_length=100)
				created	=	models.DateTimeField(auto_now_add=True)
				updated	=	models.DateTimeField(auto_now=True)
				paid	=	models.BooleanField(default=False)
				class	Meta:
								ordering	=	('-created',)
				def	__str__(self):
								return	'Order	{}'.format(self.id)
				def	get_total_cost(self):
								return	sum(item.get_cost()	for	item	in	self.items.all())
class	OrderItem(models.Model):
				order	=	models.ForeignKey(Order,
																														related_name='items',
																														on_delete=models.CASCADE)
				product	=	models.ForeignKey(Product,
																																related_name='order_items',
																																on_delete=models.CASCADE)
				price	=	models.DecimalField(max_digits=10,	decimal_places=2)
				quantity	=	models.PositiveIntegerField(default=1)
				def	__str__(self):
					   return	'{}'.format(self.id)
				def	get_cost(self):
								return	self.price	*	self.quantity

shoppingCart/models.py
from django.db import models

# Create your models here.
from	django.db	import	models
from	django.urls	import	reverse

class	Category(models.Model):
	name	=	models.CharField(max_length=200,db_index=True)
	slug	=	models.SlugField(max_length=200,unique=True)
	class	Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'
	def __str__(self):
		return self.name
	def	get_absolute_url(self):
		return	reverse('shop:product_list_by_category',args=[self.slug])

class	Product(models.Model):
	category	=	models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
	name	=	models.CharField(max_length=200,	db_index=True)
	slug	=	models.SlugField(max_length=200,	db_index=True)
	image	=	models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
	description	=	models.TextField(blank=True)
	price	=	models.DecimalField(max_digits=10,	decimal_places=2)
	available	=	models.BooleanField(default=True)
	created	=	models.DateTimeField(auto_now_add=True)
	updated	=	models.DateTimeField(auto_now=True)
	class	Meta:
		ordering	=	('name',)
		index_together	=	(('id',	'slug'),)
	def	__str__(self):
		return	self.name
	def	get_absolute_url(self):
		return	reverse('shop:product_detail',args=[self.id,self.slug])

cart/forms.py
from	django	import	forms
PRODUCT_QUANTITY_CHOICES	=	[(i,	str(i))	for	i	in	range(1,	21)]
class	CartAddProductForm(forms.Form):
				quantity	=	forms.TypedChoiceField(
																																choices=PRODUCT_QUANTITY_CHOICES,
																																coerce=int)
				update	=	forms.BooleanField(required=False,
																																initial=False,
																																widget=forms.HiddenInput)

orders/forms.py
from	django	import	forms
from	.models	import	Order
class	OrderCreateForm(forms.ModelForm):
				class	Meta:
								model	=	Order
								fields	=	['first_name',	'last_name',	'email',	'address','postal_code',	'city']

cart/views.py
# Create your views here.
from	django.shortcuts	import	render,	redirect,	get_object_or_404
from	django.views.decorators.http	import	require_POST
from	shoppingCart.models	import	Product
from	.cart	import	Cart
from	.forms	import	CartAddProductForm
@require_POST
def	cart_add(request,	product_id):
				cart	=	Cart(request)
				product	=	get_object_or_404(Product,	id=product_id)
				form	=	CartAddProductForm(request.POST)
				if	form.is_valid():
								cd	=	form.cleaned_data
								cart.add(product=product,
																	quantity=cd['quantity'],
																	update_quantity=cd['update'])
				return	redirect('cart:cart_detail')
def	cart_remove(request,	product_id):
				cart	=	Cart(request)
				product	=	get_object_or_404(Product,	id=product_id)
				cart.remove(product)
				return	redirect('cart:cart_detail')
def	cart_detail(request):
				cart	=	Cart(request)
				for	item	in	cart:
					   item['update_quantity_form']	=	CartAddProductForm(initial={'quantity':	item['quantity'],'update':	True})
				return	render(request,	'cart/detail.html',	{'cart':	cart})

orders/views.py
from django.shortcuts import render

# Create your views here.
from	.models	import	OrderItem
from	.forms	import	OrderCreateForm
from	cart.cart	import	Cart
def	order_create(request):
				cart	=	Cart(request)
				if	request.method	==	'POST':
								form	=	OrderCreateForm(request.POST)
								if	form.is_valid():
												order	=	form.save()
												for	item	in	cart:
																OrderItem.objects.create(order=order,product=item['product'],price=item['price'],quantity=item['quantity'])
												#	clear	the	cart
												cart.clear()
												return	render(request,'orders/order/created.html',{'order':	order})
				else:
								form	=	OrderCreateForm()
				return	render(request,'orders/order/create.html',{'cart':	cart,	'form':	form})

shoppingCart/views.py
from django.shortcuts import render
from	cart.forms	import	CartAddProductForm
# Create your views here.
from	django.shortcuts	import	render,	get_object_or_404
from	.models	import	Category,	Product
def	product_list(request,	category_slug=None):
	category	=	None
	categories	=	Category.objects.all()
	products	=	Product.objects.filter(available=True)
	if	category_slug:
		category	=	get_object_or_404(Category,	slug=category_slug)
		products	=	products.filter(category=category)
	return	render(request,'shop/product/list.html',{'category':category,'categories':	categories,
		'products':	products})

def	product_detail(request,	id,	slug):
	product	=	get_object_or_404(Product,id=id,slug=slug,available=True)
	cart_product_form	=	CartAddProductForm()
	return	render(request,'shop/product/detail.html',{'product':	product,'cart_product_form':cart_product_form})

cart/templates/cart/detail.html
{%	extends	"shop/base.html"	%}
{%	load	static	%}
{%	block	title	%}
		Your	shopping	cart
{%	endblock	%}
{%	block	content	%}
		<h1 class="btn btn-primary btn-lg disabled ">Your	shopping	cart</h1>
		<div class="table-responsive-sm">
		<table	class="cart table font-weight-bold pl-2 " >

				<thead class="">
						<tr>
								<th>Image</th>
								<th>Product</th>
								<th>Quantity</th>
								<th>Remove</th>
								<th>Unit	price</th>
								<th>Price</th>
						</tr>
				</thead>
				<tbody>
					{%	for	item	in	cart	%}
								{%	with	product=item.product	%}
										<tr>
												<td>
														<a	href="{{	product.get_absolute_url	}}">
																<img	src="{{	product.image.url	}}" style="width: 12rem;height: 12rem">
														</a>
												</td>
												<td>{{	product.name	}}</td>
												<td>
											<form	action="{%	url	'cart:cart_add'	product.id	%}"	method="post">	{{	item.update_quantity_form.quantity	}}
													{{	item.update_quantity_form.update	}}
													<input	type="submit"	value="Update" class="btn btn-success">
													{%	csrf_token	%}
											</form>
           </td>
												<td><a	href="{%	url	'cart:cart_remove' product.id	%}" class="btn btn-danger">Remove</a></td>
												<td	class="num">Rs {{	item.price	}}</td>
												<td	class="num">Rs {{	item.total_price	}}</td>
										</tr>
								{%	endwith	%}
						{%	endfor	%}
						<tr	class="total">
								<td>Total</td>
								<td	colspan="4"></td>
								<td	class="num">Rs {{	cart.get_total_price	}}</td>
						</tr>
				</tbody>
		</table>
	</div>
		<p	class="text-center mr-2">
				<a	href="{%	url	'shop:product_list'	%}"	class="btn btn-success">Continue	shopping</a>
				<a	href="{%	url	'orders:order_create'	%}"	class="btn btn-primary">
		Checkout
</a>
		</p>
{%	endblock	%}

orders/templates/orders/order/create.html
{%	extends	"shop/base.html"	%}
{%	block	title	%}
		Checkout
{%	endblock	%}
{%	block	content	%}
<head>
	<style type="text/css">
		input{
			display: block;
    width: 50%;
    padding: .375rem .75rem;
    font-size: 1rem;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
    margin-left: 2rem;
		}
		label{
			margin-left: 2rem;
		}
	</style>
</head>
		<h1>Checkout</h1>
		<div	class="order-info ml-2 text-danger">
				<h3 >Your	order</h3>
				<ul>
						{%	for	item	in	cart	%}
								<li>
										{{	item.quantity	}} x	{{	item.product.name	}}
										<span>Rs {{	item.total_price	}}</span>
								</li>
						{%	endfor	%}
				</ul>
				<p class="ml-2 font-weight-bold">Total:	Rs {{	cart.get_total_price	}}</p>
		</div>
		<form	action="."	method="post"	class="order-form ">
			<div class="form-group">
				{{	form.as_p	}}
				<p><input	type="submit"	value="Place	order" class="btn btn-success"></p>
				{%	csrf_token	%}
		</div>
		</form>
{%	endblock	%}

orders/templates/orders/order/created.html
{%	extends	"shop/base.html"	%}
{%	block	title	%}
		Thank	you
{%	endblock	%}
{%	block	content	%}
		<h1 class="text-center text-success font-weight-bold">Thank	you</h1>
		<p class="text-center " style="font-size: 30px">Your	order	has	been	successfully	completed.	Your	order	number	is		
		<strong>{{	order.id	}}</strong>.</p>
{%	endblock	%}

shoppingCart/templates/shop/base.html
{%	load	static	%}
<!DOCTYPE	html>
<html>
<head>
		<meta	charset="utf-8"	/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>{%	block	title	%}My	shop{%	endblock	%}</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body><div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand font-weight-bold" href="/">My	shop</a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
     
    </ul>
    <div	id="subheader">
			<div	class="cart font-weight-bold">
		    {%	with	total_items=cart|length	%}
				{%	if	cart|length	>	0	%}
					<span class="text-white">	Your	cart:</span>
			<a	href="{%	url	'cart:cart_detail'	%}" class="btn btn-success my-2 my-sm-0">
					{{	total_items	}}	item{{	total_items|pluralize	}} , Rs {{	cart.get_total_price	}}
						</a>
				{%	else	%}
					<span class="text-white">Your	cart	is	empty.</span>
				{%	endif	%}
		    {%	endwith	%}
        </div>

		</div>
  </div>
</nav>

		
		<div	id="content">
				{%	block	content	%}
				{%	endblock	%}
		</div>
	</div>
</body>
</html>

shoppingCart/templates/shop/product/detail.html
{%	extends	"shop/base.html"	%}
{%	load	static	%}
{%	block	title	%}
		{{	product.name	}}
{%	endblock	%}
{%	block	content	%}
		<div	class="product-detail d-flex font-weight-bold row">
				<div class="m-2  col-sm" >
				<img	src="{{	product.image.url	}}" style="min-width:14rem;max-width:24rem;max-height:24rem" >
			    </div>
			    <div class="m-2  col-sm " >
				<h1>{{	product.name	}}</h1>
				<h2><a	href="{{	product.category.get_absolute_url	}}">{{product.category}}</a></h2>
				<p	class="price">Rs {{	product.price	}}</p>
				<form	action="{%	url	'cart:cart_add' product.id	%}"	method="post">
		{{	cart_product_form	}}
		{%	csrf_token	%}
		<input	type="submit" class="btn btn-success"	value="Add	to	cart">
                </form>
                <br>
				{{	product.description|linebreaks	}}
		</div>
	</div>
{%	endblock	%}

shoppingCart/templates/shop/product/list.html
{%	extends	"shop/base.html"	%}
{%	load	static	%}
{%	block	title	%}
		{%	if	category	%}{{	category.name	}}{%	else	%}Products{%	endif	%}
{%	endblock	%}
{%	block	content	%}
        <div class="d-flex  float-left row">
        	<div class="card  col-sm" >
			  <div class="card-body" style="width: 14rem;">
			    <h3 class="card-title card-header">Categories</h3>
			    <br>
			    <h6 class="card-subtitle mb-2 text-muted"><ul>
						<li	{%	if	not	category	%}class="selected"{%	endif	%}>
								<a	href="{%	url	'shop:product_list'	%}">All</a>
						</li>
						{%	for	c	in	categories	%}
								<li	{%	if	category.slug	==	c.slug	%}class="selected"
								{%	endif	%}>
										<a	href="{{	c.get_absolute_url	}}">{{	c.name	}}</a>
								</li>
						{%	endfor	%}
				</ul></h6>
			   
			  </div>
			</div>

		
    <div	id="main"	class="product-list ">
		<div class="ml-3"><h1>{%	if	category	%}{{	category.name	}}{%	else	%}Products
		{%	endif	%}</h1>
	</div>
	 <div	id="main"	class="product-list card-deck ml-3 " style="max-width: 66rem;">
    
		{%	for	product	in	products	%}
		
		<div class="card ml-2 mb-3 col-sm" style="min-width: 13rem;max-width: 18rem" class="item">
        <a	href="{{	product.get_absolute_url	}}">
        <img class="card-img-top" src="{%	if	product.image	%}{{	product.image.url	}}{%	endif	%}" alt="Card image cap">
        </a>
        <div class="card-body">
        	<a	href="{{	product.get_absolute_url	}}">{{	product.name	}}</a>
								<br>
								Rs {{	product.price	}}
       
        </div>
        </div>
        
        {%	endfor	%}
		</div>
	</div>
	</div>
{%	endblock	%}